version: '3'
services:
  docker-robot:
    network_mode: host
    build: ./docker-robot
    image: docker-robot
    container_name: docker-robot-container
    environment:
      - ROS_DOMAIN_ID=102
      - TERM='xterm-256color'
    devices:
      - /dev/ttyTHS1
      - /dev/ydlidar
        # - /sys/bus/usb/001/009
    volumes:
      - /home/nvidia/INF3995-Robot:/root/INF3995-Robot
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash -c "/root/clean_workspace.sh && source /opt/ros/humble/setup.bash && cd root && /root/deploy-robot.sh && source /root/INF3995-Robot/ros_ws/install/setup.bash && ros2 launch py_identify_server identify.launch.py"
